### ISSUE TITLE
query about the `rangeSmooth` argument and how it works

### ISSUE THREAD

**Issue by Rohit-Satyam** [MiguelMSandin/random#1]
Hi @MiguelMSandin 

Thanks for writing these python utilities. They have proven to be super helpful. My query is regarding the code that you use for Smoothening of Shannon entropy. This value is easy to visualize in R and gives a neat line plot as compared to when one uses actual Shannon-entropy values. I wrote an equivalent code in R to understand what it does and I observe that for first 50 position, the window size increases by 1 bp (b stays constant while e increases). That means the average entropy reported for 1st base is average of  first fifty entropy value, for 2nd it's first 51 entropy value's mean, for 3rd it's first 52 entropy value's mean and so on until after 50th base where the window size is kept fixed(`rangeSmooth *2=100 if default is used`) until last 50 bases are encountered. 

My query is, is this standard way because I understood this as a rolling mean of entropies being reported. If it is not rolling average what exactly should I call it and how can you say that a fixed window size of 100 bp is used when first 50 bases and last 50 bases have smaller windows (<100).

```r
for (i in 1:length(dft$shan)) {
    if (i - rangeSmooth < 1) {
        b <- 1
        print(paste("b:",b,"for", i))
        df[i,]$b <- b
    } else {
        b <- i - rangeSmooth
        print(paste("b:",b,"for", i))
        df[i,]$b <- b
    } 
    if (i + rangeSmooth > length(dft$shan)) {
        e <- length(dft$shan)
        print(paste("e:",e,"for", i))
        df[i,]$e <- e
    } else {
        e <- i + rangeSmooth
        print(paste("e:",e,"for", i))
        df[i,]$e <- e
    } 
    df[i,]$smooth <- as.character(mean(dft$shan[b:e]))
    df[i,]$i <- i
}
```

Next what threshold should I use to say that the mean entropy value (smooth field) is smaller enough for a region to be considered as conserved (Below is how I plot the smooth column values and I use a horizontal threshold based on actual Entropy Value rather than smoothened entropy)? Besides, is this way of smoothening published somewhere so that I can go read more about it? I am not sure if the entropy spike seen in first and last 50 bp is due to smaller window (because we are slowly increasing it to 100) because in my alignment there are lot of gaps in the beginning and there per base entropy is less than `0.05` (see the read line gap score plot below)

Beside, I am planning to use your code in a way to write a function in an R package so it will be very helpful, if you could clear my doubts

![image](https://github.com/MiguelMSandin/random/assets/55479480/21274c5a-5835-45a7-b3ce-e2043ee99a3f)

PS: Adding a reference for people who also have confusion why some Shannon Entropy Values are greater than 1 in their results because I had similar query myself. Read [here](https://www.researchgate.net/post/When-I-am-using-the-Shannon-index-to-compare-between-richness-of-biodiversity-within-different-habitats-is-it-possible-to-get-the-value-of-Shannon-greater-than-4-or-9)

**Comment by MiguelMSandin** [comment]
Hi Rohit, thanks for using my scripts. And specially for calling them 'helpful'!

**Regarding the moving average question**: You raised an important issue that it is intrinsic to the sliding window approach when calculating unweighted averages. The window is simply truncated to the available data.
If you are still bother by this problem: one solution could be to remove the first and last 'window/2' positions so all smoothed points are calculated from the same number of observations (e.g.; with a sliding-window of 100 bp, delete the first and last 50 points of the smoothed data, as in 'rollmean' from the R package '[zoo](https://cran.r-project.org/web/packages/zoo/index.html)'). Another solution could be to use a different smoothing approach, such as parametric distributions or functions.

**Regarding Shannon entropy values**: Shannon entropy measures the [information or uncertainty inherent to the variable's possible outcomes](https://en.wikipedia.org/wiki/Entropy_(information_theory)), not the probability. Therefore whether a Shannon entropy value is high or low might be relative to the rest of the data, regardless of arbitrary thresholds.

I guess you are referring all along to the function [alignmentEntropy.py](https://github.com/MiguelMSandin/random/blob/main/fasta/alignmentEntropy.py), but correct me if I'm wrong. Then in your example, if you want to remove the effect of the gaps from the smoothed value you can quickly check it out by setting the option `-g/--gaps`. From my experience, gappy regions tend to show higher entropy, since they are difficult to align due to their differences. But then you should consider more biological than technical questions regarding the scope of your study.

Shannon Entropy is not likelihood, and therefore the maximum value is not 1. It is actually log(*k*), where *k* is the total count of individual observations (or groups) representing maximum evenness (so the highest possible entropy). If you are using nucleotide data (so A, C, T, G, and no ambiguities nor gaps), then log(4)=1.386294 (in base *e*, the default in the function mentioned above).

Hope this was helpful.

Lastly, and just as a disclaimer, I'm a biologist, with very limited training in statistics and nothing at all in bioinformatics, so please understand errors or non-optimal scripting.

**Comment by MiguelMSandin** [comment]
If no more questions, I will close this issue
